---
settings:
  name: Converged Systems Advisor
  rss_page: reference_new.html
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: Converged Systems Advisor docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new
          url: /reference_new.html
        - title: What's new archive
          url: /reference_archive.html
        - title: Known issues
          url: /reference_issues.html
    - title: Concepts
      entries:
        - title: Overview
          url: /concept_overview.html
        - title: Architecture
          url: /concept_architecture.html
        - title: Licensing
          url: /concept_licensing.html
        - title: Security
          url: /concept_security.html
        - title: User roles
          url: /reference_user_roles.html
    - title: Getting started
      entries:
        - title: Quick start
          url: /task_quick_start.html
        - title: Prepare your environment
          url: /task_prepare_environment.html
        - title: Create accounts for FlexPod devices
          url: /task_create_accounts_flexpod_devices.html
        - title: Set up and deploy agent
          url: /task_setup_deploy_agent.html
        - title: Add infrastructure in the portal
          url: /task_add_infrastructure.html
        - title: Configure notifications
          url: /task_configure_notifications.html
        - title: Set a static IP on the agent
          url: /task_setting_static_ip.html
    - title: Monitoring your infrastructure
      entries:
        - title: Review your infrastructure history
          url: /task_review_infrastructure_history.html
        - title: Monitor rules
          url: /task_monitor_rules.html
        - title: Generate reports
          url: /task_generate_reports.html
        - title: Track support contracts
          url: /task_track_contracts.html
    - title: Validate deployment for partners and resellers
      url: /task_deployment_validation_partners_resellers.html
    - title: Troubleshooting
      url: /task_troubleshooting.html
    - title: Related links
      url: /reference_additional_info.html
    - title: Legal notices
      url: /reference_legal_notices.html
