---
sidebar: sidebar
permalink: reference_new.html
keywords: new, features, what's new, enhancements, release notes
summary: NetApp periodically updates Converged Systems Advisor to bring you new features, enhancements, and bug fixes.
---

= What's new in Converged Systems Advisor
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp periodically updates Converged Systems Advisor to bring you new features, enhancements, and bug fixes.

To confirm FlexPod components are supported by the CSA agent, reference the http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^] (IMT).

== 30 July 2020

The release includes the following enhancements:

* <<New functionality for storage change detection (diffs)>>
* <<Expanded configuration assurance for cluster interconnect switches>>
* <<Initial coverage of NVMe designs>>

== New functionality for storage change detection (diffs)

Now you can detect changes that have occurred on the storage system.  To check for change, from the *Storage Inventory* pages, click *View Configuration Difference*.  Then, select a previous configuration data and time, which will be compared to the most recent storage configuration.  Any changes that have occurred will be highlighted for quick review.

== Expanded configuration assurance for cluster interconnect switches

In the Converged Systems Advisor portal, the configuration assurance checks have been expanded to monitor the supportability of ONTAP cluster interconnect switching for the following models:

* Cisco Nexus 3132Q-V
* Cisco Nexus 3232C
* Cisco Nexus 92300YC

== Initial coverage of NVMe designs

Initial configuration assurance checks have been added to monitor supportability of NVMe ONTAP storage designs in FlexPod.
