---
sidebar: sidebar
permalink: task_setting_static_ip.html
keywords: networking, ip address, static, static ip, agent
summary: If your environment does not have a DHCP server, you can set a static IP address on the Converged Systems Advisor agent.
---

= Setting a static IP address on the agent
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
If your environment does not have a DHCP server, you can set a static IP address on the Converged Systems Advisor agent.

.Steps

. Log in to the agent's virtual machine console using the VMware vSphere client.
+
The default user name is *csa* and the default password is *netapp*. Change the password, if prompted.

. Enter `sudo su –` at the csa prompt to become root.

. Enter `# systemctl stop csa.service` to stop the CSA service.

. Enter the following to determine your correct interface file name.
+
`# ls /etc/network/interfaces.d/`
`eth0`

. Enter `# /sbin/ifdown eth0` to stop the active interface.

. Edit the /etc/network/interfaces.d/eth0 file with the editor of your choice.
+
`# nano /etc/network/interfaces.d/`
`eth0`
or
`# vi /etc/network/interfaces.d/`
`eth0`
+
The file contains the following:
+
`allow-hotplug eth0`
`iface eth0 inet dhcp`

. Remove `iface eth0 inet dhcp` and add the following.
NOTE: You must substitute the correct values for all  the entries that follow the field names in the example below.  For instance, `192.168.11.1` is the value for the gateway in the example.  However, instead of `192.168.11.1`, you should enter the correct address for your gateway.
+
`iface eth0 inet static`
`address 192.168.11.100`
`netmask 255.255.255.0`
`gateway 192.168.11.1`
`dns-domain example.com`
`dns-nameservers 192.168.11.1`

. Save the file.
+
In nano, you enter *ctrl + o* followed by *ctrl + x* to save.

. Enter `# ifup eth0` to start the network interface.

. Enter `systemctl start csa.service` to restart Converged Systems Advisor.
