---
sidebar: sidebar
permalink: task_deployment_validation_partners_resellers.html
keywords: review, alerts, warnings, failed, rules, alerts, history, remediate, remediation, suppress, display, fail, warning, pass, notifications, email
summary: As a partner or reseller, you can validate the deployment of a client's infrastructure.
---

= Validate deployment for partners and resellers
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
As a partner or reseller, you can validate the deployment of your customer's infrastructure by reviewing alerts for failed rules and warnings. You can also generate a deployment validation report.

.Before you start

* You have installed a new FlexPod at your customer site, or you are working with an existing FlexPod.

* You created accounts on FlexPod devices.

* You downloaded and installed the agent.  Refer to link:task_setup_deploy_agent.html[Set up and deploy agent].

* You set up the networking for the agent, and optionally, you installed an SSL certificate on the agent.

* With your NetApp credentials, you created the CI for your customer to add the infrastructure to the portal.

* Optionally, you shared the infrastructure with other users.

* If you are using a TACACS+ server, you granted CSA user privileges.

.Steps

Partners and resellers use their own NetApp credentials to log in to their customers' systems to start the validation process.

. Log in to the https://csa.netapp.com/[Converged Systems Advisor portal^] using your NetApp credentials.

As a partner or reseller you can validate your customer's infrastructure using the follow methods:

*  On the Dashboard, you can validate various aspects of the infrastructure:

** *Firmware Interoperability* displays the installed software versions.  Click each heading to view additional details.

** *Health* graphically displays the status of rules for storage, compute, network, and virtualization capabilities of the infrastructure. Click the color areas of the graphics to view additional details.

** *Rules Summary* shows you alerts for failed rules and warnings. Click the arrows to the left of each row, or click the device name to view additional details.

* In the action bar, select *Reports*, then *Health Report*, to generate a detailed Converged System Health Report.  You can view it in the browser, download it as a PDF file, or share it via email.
